#!/usr/bin/env python3
"""Read-only, dependency-free preflight for Cloudflare website projects."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


SOURCE_SUFFIXES = {".html", ".astro", ".jsx", ".tsx", ".js", ".ts", ".vue", ".svelte", ".css", ".scss"}
SKIP_DIRS = {".git", "node_modules", ".next", ".astro", "dist", "build", ".wrangler", "coverage"}


def source_files(root: Path):
    for path in root.rglob("*"):
        if path.is_file() and path.suffix.lower() in SOURCE_SUFFIXES and not any(part in SKIP_DIRS for part in path.parts):
            yield path


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def find_named(root: Path, names: set[str]) -> list[Path]:
    return [p for p in root.rglob("*") if p.is_file() and p.name in names and not any(part in SKIP_DIRS for part in p.parts)]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("root", nargs="?", default=".")
    parser.add_argument("--json", action="store_true", dest="as_json")
    parser.add_argument("--local-service", action="store_true", help="enable local-service-specific gates")
    parser.add_argument("--strict", action="store_true", help="return non-zero for warnings as well as errors")
    args = parser.parse_args()
    root = Path(args.root).resolve()
    if not root.is_dir():
        print(f"ERROR: project root does not exist: {root}")
        return 2

    results: list[dict[str, str | bool]] = []

    def check(name: str, passed: bool, note: str, severity: str = "warning") -> None:
        results.append({"name": name, "passed": passed, "severity": severity, "note": note})

    package = root / "package.json"
    check("package.json", package.is_file(), "JavaScript project manifest")
    if package.is_file():
        try:
            data = json.loads(read_text(package))
            scripts = data.get("scripts", {})
            for name in ("build", "lint", "test", "typecheck"):
                check(f"script:{name}", name in scripts, "recommended verification command")
        except json.JSONDecodeError as exc:
            check("package-json-valid", False, f"cannot parse package.json: {exc}", "error")

    wrangler = find_named(root, {"wrangler.jsonc", "wrangler.json", "wrangler.toml"})
    pages_files = find_named(root, {"_routes.json", "_redirects", "_headers"})
    check("cloudflare-config", bool(wrangler or pages_files), "Wrangler or Pages configuration discovered")
    if wrangler:
        config_text = "\n".join(read_text(p) for p in wrangler)
        check("compatibility-date", "compatibility_date" in config_text, "Wrangler compatibility date declared")
        check("no-deprecated-workers-sites", not re.search(r'(?m)^\s*(site\s*=|\[site\])', config_text), "Workers Sites configuration is deprecated")

    gitignore = read_text(root / ".gitignore")
    check("secret-ignore", any(token in gitignore for token in (".env", ".dev.vars")), "ignore local secret files")
    exposed_secret_files = find_named(root, {".env", ".dev.vars", ".env.production", ".dev.vars.production"})
    secrets_ignored = bool(re.search(r"(?m)^\s*(?:\.env|\.dev\.vars)(?:\.\*|\*)?\s*$", gitignore))
    check("local-secrets-ignored", not exposed_secret_files or secrets_ignored, "local secret files must be ignored; also verify none are tracked", "error")

    robots = find_named(root, {"robots.txt"})
    sitemaps = find_named(root, {"sitemap.xml", "sitemap-index.xml"})
    not_found = find_named(root, {"404.html", "404.astro", "404.tsx", "404.jsx", "+error.svelte"})
    check("robots", bool(robots), "robots policy found or generated by framework")
    check("sitemap", bool(sitemaps), "sitemap file found; generated sitemaps may only exist after build")
    check("404", bool(not_found), "intentional not-found route")

    files = list(source_files(root))
    corpus = "\n".join(read_text(p) for p in files)
    lower = corpus.lower()
    robots_text = "\n".join(read_text(p) for p in robots).lower()
    check("title", "<title" in lower or "title:" in lower or "title=" in lower, "page title implementation found")
    check("description", "description" in lower, "meta description implementation found")
    check("canonical", "canonical" in lower, "canonical URL implementation found")
    check("structured-data", "application/ld+json" in lower or "schema.org" in lower, "structured data implementation found")
    check("document-language", bool(re.search(r"<html\b[^>]*\blang\s*=", corpus, re.I)), "document language declared")
    check("responsive-viewport", bool(re.search(r'<meta\b[^>]*name\s*=\s*["\']viewport["\']', corpus, re.I)), "responsive viewport declared")
    check("main-landmark", bool(re.search(r"<main\b", corpus, re.I)), "main landmark found")
    check("skip-link", bool(re.search(r'<a\b[^>]*href\s*=\s*["\']#[^"\']+["\'][^>]*>[^<]*(?:skip|main|content)', corpus, re.I)), "keyboard bypass link found")
    check("focus-visible", ":focus-visible" in lower or "focus-visible" in lower, "visible keyboard focus treatment found")
    outline_suppression = len(re.findall(r"outline\s*:\s*(?:0|none)\b", corpus, re.I))
    check("no-unreplaced-focus-suppression", outline_suppression == 0 or ":focus" in lower, f"found {outline_suppression} outline suppression occurrence(s); verify each has a visible replacement")
    accessibility_preferences = "a11y-preferences" in lower or "accessibility settings" in lower
    check("first-party-accessibility-menu", accessibility_preferences, "first-party accessibility preference control found; do not substitute an overlay script")
    accessibility_overlays = re.findall(r"accessibe|userway|accessiway|equalweb", lower, re.I)
    check("no-accessibility-overlay", not accessibility_overlays, f"third-party accessibility overlay references: {sorted(set(accessibility_overlays)) or 'none'}", "error")
    if args.local_service:
        check("local-business-entity", "localbusiness" in lower or "organization" in lower, "verified Organization/LocalBusiness entity markup required for local-service mode")
        plan = root / "website-plan"
        required_plan = {
            "fact-claim-ledger.md", "research-notes.md", "keyword-page-map.csv",
            "question-bank.md", "url-internal-link-map.csv", "location-qualification.csv",
            "accessibility-plan.md",
        }
        missing_plan = sorted(name for name in required_plan if not (plan / name).is_file())
        check("local-service-plan", not missing_plan, f"missing website-plan artifacts: {missing_plan or 'none'}", "error")
        has_phone_action = bool(re.search(r'href\s*=\s*[{"]?[^\n>]*tel:', corpus, re.I))
        has_form = bool(re.search(r'<form\b', corpus, re.I))
        check("local-service-primary-action", has_phone_action or has_form, "call or lead-form conversion path required", "error")
        if has_form:
            has_server_delivery = bool(re.search(r'/api/|send_email|lead_webhook|pages/functions|worker/', lower, re.I))
            check("lead-form-server-delivery", has_server_delivery, "lead forms require a server-side delivery path", "error")
    crawlable_links = len(re.findall(r"<a\s+[^>]*href\s*=", corpus, re.I))
    check("crawlable-internal-links", crawlable_links > 0, f"found {crawlable_links} crawlable anchor implementation(s)")

    oai_blocked = bool(re.search(r"user-agent\s*:\s*oai-searchbot[\s\S]{0,300}?disallow\s*:\s*/", robots_text, re.I))
    check("oai-searchbot", not oai_blocked, "OAI-SearchBot is not explicitly blocked; also verify Cloudflare WAF/bot rules")
    check("indexnow", "indexnow" in lower or bool(find_named(root, {"indexnow-key.txt"})), "optional IndexNow integration for changed URLs")

    transition_all = len(re.findall(r"transition\s*:\s*all\b", corpus, re.I))
    scale_zero = len(re.findall(r"scale\(\s*0(?:[),\s])", corpus, re.I))
    check("no-transition-all", transition_all == 0, f"found {transition_all} transition: all occurrence(s)")
    check("no-scale-zero-entry", scale_zero == 0, f"found {scale_zero} scale(0) occurrence(s); review entry animations")
    check("reduced-motion", "prefers-reduced-motion" in lower, "intentional reduced-motion behavior found")
    third_party_motion = bool(
        re.search(r"\b(?:dotlottie|lottie|rive|gsap|scrolltrigger)\b", lower, re.I)
    )
    motion_ledger = root / "website-plan" / "motion-license-ledger.md"
    check("motion-license-ledger", not third_party_motion or motion_ledger.is_file(), "third-party motion requires website-plan/motion-license-ledger.md")

    ai_phrases = [
        "in today's fast-paced world", "unlock your", "elevate your", "cutting-edge",
        "seamless experience", "tailored solutions", "trusted partner", "transform your vision",
    ]
    phrase_hits = {phrase: lower.count(phrase) for phrase in ai_phrases if phrase in lower}
    check("human-copy", not phrase_hits, f"generic phrase hits: {phrase_hits or 'none'}")

    if args.as_json:
        print(json.dumps({"root": str(root), "results": results}, indent=2))
    else:
        for item in results:
            status = "PASS" if item["passed"] else item["severity"].upper()
            print(f"{status:7} {item['name']}: {item['note']}")
        failures = sum(not item["passed"] for item in results)
        errors = sum(not item["passed"] and item["severity"] == "error" for item in results)
        print(f"\nPreflight complete: {len(results) - failures} passed, {failures} findings, {errors} errors.")

    has_errors = any(not item["passed"] and item["severity"] == "error" for item in results)
    has_findings = any(not item["passed"] for item in results)
    return 1 if has_errors or (args.strict and has_findings) else 0


if __name__ == "__main__":
    raise SystemExit(main())
