#!/usr/bin/env python3
"""Read-only, dependency-free preflight for Cloudflare website projects."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


SOURCE_SUFFIXES = {".html", ".astro", ".jsx", ".tsx", ".js", ".ts", ".vue", ".svelte", ".css", ".scss"}
SKIP_DIRS = {".git", "node_modules", ".next", ".astro", "dist", "build", ".wrangler", "coverage"}


def source_files(root: Path):
    for path in root.rglob("*"):
        if path.is_file() and path.suffix.lower() in SOURCE_SUFFIXES and not any(part in SKIP_DIRS for part in path.parts):
            yield path


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def find_named(root: Path, names: set[str]) -> list[Path]:
    return [p for p in root.rglob("*") if p.is_file() and p.name in names and not any(part in SKIP_DIRS for part in p.parts)]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("root", nargs="?", default=".")
    parser.add_argument("--json", action="store_true", dest="as_json")
    args = parser.parse_args()
    root = Path(args.root).resolve()
    if not root.is_dir():
        print(f"ERROR: project root does not exist: {root}")
        return 2

    results: list[dict[str, str | bool]] = []

    def check(name: str, passed: bool, note: str, severity: str = "warning") -> None:
        results.append({"name": name, "passed": passed, "severity": severity, "note": note})

    package = root / "package.json"
    check("package.json", package.is_file(), "JavaScript project manifest")
    if package.is_file():
        try:
            data = json.loads(read_text(package))
            scripts = data.get("scripts", {})
            for name in ("build", "lint", "test", "typecheck"):
                check(f"script:{name}", name in scripts, "recommended verification command")
        except json.JSONDecodeError as exc:
            check("package-json-valid", False, f"cannot parse package.json: {exc}", "error")

    wrangler = find_named(root, {"wrangler.jsonc", "wrangler.json", "wrangler.toml"})
    pages_files = find_named(root, {"_routes.json", "_redirects", "_headers"})
    check("cloudflare-config", bool(wrangler or pages_files), "Wrangler or Pages configuration discovered")
    if wrangler:
        config_text = "\n".join(read_text(p) for p in wrangler)
        check("compatibility-date", "compatibility_date" in config_text, "Wrangler compatibility date declared")
        check("no-deprecated-workers-sites", not re.search(r'(?m)^\s*(site\s*=|\[site\])', config_text), "Workers Sites configuration is deprecated")

    gitignore = read_text(root / ".gitignore")
    check("secret-ignore", any(token in gitignore for token in (".env", ".dev.vars")), "ignore local secret files")
    exposed_secret_files = find_named(root, {".env", ".dev.vars", ".env.production", ".dev.vars.production"})
    check("no-local-secrets", not exposed_secret_files, "local secret files present; verify they are ignored and never committed", "error")

    robots = find_named(root, {"robots.txt"})
    sitemaps = find_named(root, {"sitemap.xml", "sitemap-index.xml"})
    not_found = find_named(root, {"404.html", "404.astro", "404.tsx", "404.jsx", "+error.svelte"})
    check("robots", bool(robots), "robots policy found or generated by framework")
    check("sitemap", bool(sitemaps), "sitemap file found; generated sitemaps may only exist after build")
    check("404", bool(not_found), "intentional not-found route")

    files = list(source_files(root))
    corpus = "\n".join(read_text(p) for p in files)
    lower = corpus.lower()
    robots_text = "\n".join(read_text(p) for p in robots).lower()
    check("title", "<title" in lower or "title:" in lower or "title=" in lower, "page title implementation found")
    check("description", "description" in lower, "meta description implementation found")
    check("canonical", "canonical" in lower, "canonical URL implementation found")
    check("structured-data", "application/ld+json" in lower or "schema.org" in lower, "structured data implementation found")
    check("local-business-entity", "localbusiness" in lower or "organization" in lower, "Organization/LocalBusiness entity markup found when applicable")
    crawlable_links = len(re.findall(r"<a\s+[^>]*href\s*=", corpus, re.I))
    check("crawlable-internal-links", crawlable_links > 0, f"found {crawlable_links} crawlable anchor implementation(s)")

    oai_blocked = bool(re.search(r"user-agent\s*:\s*oai-searchbot[\s\S]{0,300}?disallow\s*:\s*/", robots_text, re.I))
    check("oai-searchbot", not oai_blocked, "OAI-SearchBot is not explicitly blocked; also verify Cloudflare WAF/bot rules")
    check("indexnow", "indexnow" in lower or bool(find_named(root, {"indexnow-key.txt"})), "optional IndexNow integration for changed URLs")

    transition_all = len(re.findall(r"transition\s*:\s*all\b", corpus, re.I))
    scale_zero = len(re.findall(r"scale\(\s*0(?:[),\s])", corpus, re.I))
    check("no-transition-all", transition_all == 0, f"found {transition_all} transition: all occurrence(s)")
    check("no-scale-zero-entry", scale_zero == 0, f"found {scale_zero} scale(0) occurrence(s); review entry animations")
    check("reduced-motion", "prefers-reduced-motion" in lower, "intentional reduced-motion behavior found")

    ai_phrases = [
        "in today's fast-paced world", "unlock your", "elevate your", "cutting-edge",
        "seamless experience", "tailored solutions", "trusted partner", "transform your vision",
    ]
    phrase_hits = {phrase: lower.count(phrase) for phrase in ai_phrases if phrase in lower}
    check("human-copy", not phrase_hits, f"generic phrase hits: {phrase_hits or 'none'}")

    if args.as_json:
        print(json.dumps({"root": str(root), "results": results}, indent=2))
    else:
        for item in results:
            status = "PASS" if item["passed"] else item["severity"].upper()
            print(f"{status:7} {item['name']}: {item['note']}")
        failures = sum(not item["passed"] for item in results)
        errors = sum(not item["passed"] and item["severity"] == "error" for item in results)
        print(f"\nPreflight complete: {len(results) - failures} passed, {failures} findings, {errors} errors.")

    return 1 if any(not item["passed"] and item["severity"] == "error" for item in results) else 0


if __name__ == "__main__":
    raise SystemExit(main())
